# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Manhattan distance between two matrices
#'
#' Implemented in Rcpp
#'
#' @param x Matrix 1
#' @param y Matrix 2
#'
#' @export
#'
manhattan_distance <- function(x, y) {
    .Call('_dynutils_manhattan_distance', PACKAGE = 'dynutils', x, y)
}

